### ISSUE TITLE
Doesn't work with the PC version of Tales of Vesperia: Definitive Edition?

### ISSUE THREAD

**Issue by marceau-maubert** [AdmiralCurtiss/HyoutaTools#11]
I've tried following instructions as follows here: https://github.com/AdmiralCurtiss/HyoutaTools/issues/3#issuecomment-451749709

I couldn't get NUB files extracted from SE3 files via HyoutaTools to be recognized by vgmstream, HyoutaTools or NUBExt r12. I imagine the file format is ever so slightly updated from the console editions of the game, but I don't know how I could help with that myself although I would like to.

![ShareX_WPBKJyqw2j](https://user-images.githubusercontent.com/3979239/98732661-ba760100-239f-11eb-976d-c789bed96dcd.png)

The funny thing is that NUBExt does actually recognize NUB files the game ships with:

![NUBExt_r12beta_bDOIrb6jUo](https://user-images.githubusercontent.com/3979239/98732667-bd70f180-239f-11eb-808e-9353b13466f9.png)

Sorry if this is kind of a useless issue but maybe there's some way to get it working?

**Comment by AdmiralCurtiss** [comment]
Ah yeah that description was for the 360 file format, the PC version uses the PS3 format instead. Gimme a bit, I should have instructions for those somewhere...

**Comment by AdmiralCurtiss** [comment]
Ooops I'm an idiot and didn't read my own linked post, haha, that had the PS3 instructions too.

Yeah apparently the PC version changed the skit audio storage location completely, it's now in `Data64\chat_swf\SkitSoundFiles.awb`. vgmstream can read those by itself, if you're using foobar just open the `awb` file directly and it'll list all of the audio clips in it. If you're using vgmstream's `test.exe` to convert do `FOR /L %G IN (1,1,1104) DO test -s %G -o tovskit_%G.wav SkitSoundFiles.awb`.

**Comment by marceau-maubert** [comment]
I was looking for sound effects rather than voice files.

**Comment by AdmiralCurtiss** [comment]
Oh, I've never extracted those, but I think those are the `STC_*.SE3` files in `Data64\snd`? And you're right, my SE3toNUB doesn't seem to work on those. Format looks simple enough though, let's see...

**Comment by AdmiralCurtiss** [comment]
Okay, that should do it. `HyoutaToolsCLI se3tonub STC_EVT.SE3` ->`HyoutaToolsCLI tales.vesperia.nub.extract STC_EVT.SE3.nub` should give you usable files.

Some of the bnsf files don't seem to be correctly decoded by vgmstream, but I believe that is a vgmstream bug or unsupported feature. I've seen files like that before as well in Graces.

The SE3 also contains filenames that I'm currently ignoring, might be nice to keep those on extraction. Might add that in an hour or two.

**Comment by marceau-maubert** [comment]
Excellent, I'll try it out, thanks for the swift answers.

**Comment by AdmiralCurtiss** [comment]
FYI, I've now implemented direct SE3 extraction with `Tales.Vesperia.SE3.Extract`, which keeps the filenames.
