### ISSUE TITLE
Vesperia GUI Problems

### ISSUE THREAD

**Issue by luis-elias** [AdmiralCurtiss/HyoutaTools#14]
I'm trying to work with PC Vesperia files and I was able to build and run both GUI and CLI. The files I want to work with are in the item.svo file and the CLI version of the tool doesn't let me access the ItemDat viewer. It says it's supported in the GUI version of the tool, but I can't get anything to work with the GUI version, I've tried all sorts of ways to type in the commands, but I can't get anything to work with it. The run button doesn't seem to do anything. Is there some sort of guide to using the GUI tool? I appreciate any help on this topic!

**Comment by AdmiralCurtiss** [comment]
I admit I haven't run the GUI tool in years, it was only used back during the PS3 fan-translation/website dev, it's entirely plausible I broke it somehow. Let's see...

**Comment by AdmiralCurtiss** [comment]
Okay this is not perfect yet but try running, from cmd:

~~~
HyoutaToolsGUI Tales.Vesperia.ItemDat.Viewer PC 2 "d:\SteamLibrary\steamapps\common\Tales of Vesperia Definitive Edition\Data64"
~~~

(replace game path as appropriate)

Run just

~~~
HyoutaToolsGUI Tales.Vesperia.ItemDat.Viewer
~~~

to get a usage guideline.

Does that help?

**Comment by luis-elias** [comment]
I don't know what I was doing wrong, but I re-built everything and attempted your suggestion and it worked like a charm! Thank you so much. I am going to close it, because you helped solve my problem
