### ISSUE TITLE
Can't unpack *.nub-file from Tales of Vesperia

### ISSUE THREAD

**Issue by LabMember12** [AdmiralCurtiss/HyoutaTools#20]
Hello, sorry for bothering. I compiled build in Visual Studio 2022 without errors. Then tried to extract music from *.nub-file in Tales of Vesperia (PC) just to get empty folder and nothing else. Any solution?

![image](https://user-images.githubusercontent.com/115190459/194418443-90932334-dcff-420a-ab40-647965ad028b.png)

**Comment by AdmiralCurtiss** [comment]
Looks like the endian detection fails and it tries to read millions of file entries.

**Comment by LabMember12** [comment]
Thanks for quick reply.) Damn, that was last hope to get music (and possibly replace) somehow. :P I guess problem with nub-files in PC version in general. When I checked SE3 file it got extracted fine.

**Comment by AdmiralCurtiss** [comment]
Okay, I pushed a fix, changed the autodetection a little and you can also override it now if it fails. All the PC and PS3 files seem to extract fine now, though vgmstream can't seem to play a lot of them -- not sure if that's my fault or vgmstream's.

**Comment by AdmiralCurtiss** [comment]
FYI if you want to play around with this, there's bnsf encoder source code available at https://www.itu.int/rec/T-REC-G.722.1-200505-I/en

**Comment by LabMember12** [comment]
Thank you very much! I will check update tomorrow and post here.

**Comment by AdmiralCurtiss** [comment]
Okay, files should play fine in vgmstream now too. It was half and half, vgmstream is very picky about the filesize and chokes if the file has padding, but the music ones were my fault because I truncated the header (since the music files have looping info their header is longer than the voice files).

**Comment by LabMember12** [comment]
Thanks again! Now it works great, got unpacked everything. I'll use vgmstream for simple playback. Also will try to learn how to pack it back, so thanks for remark about decoder too. Much appreciated!

**Comment by LabMember12** [comment]
Checked encoder to get errors in compilation process. Maybe I'm just too stupid for that eeh.
![image](https://user-images.githubusercontent.com/115190459/194625624-cbd1f194-5c9e-4a85-a932-79d93ddb6e5f.png)

**Comment by AdmiralCurtiss** [comment]
The encoder source code is quite old so you probably have to replace a few typedefs and/or names and maybe add a few includes. Shouldn't be too hard to get running though, I remember getting it working a few years ago (on Windows at least).

**Comment by LabMember12** [comment]
Yeah, you right. Too bad my knowledge is enough or recent VS only. :( Anyway, huge thanks, man, was great help with general extraction! I dunno, maybe will try to find skilled guy to get this mess. I also checked it with VS2005 and had no luck as well sadly.

**Comment by LabMember12** [comment]
Today I was able to compile it without much troubles. I installed Visual Studio 2003 (somehow, it still works on W10), then converted sources and managed to build executable. So, you was completely right, while I'm panicker sometimes. Thank you very much again!
![image](https://user-images.githubusercontent.com/115190459/194715307-14912a04-784d-4f7e-bf85-b48d23c7eeaa.png)
