### ISSUE TITLE
Problem with rebuild of *.NUB-pack in TOV

### ISSUE THREAD

**Issue by LabMember12** [AdmiralCurtiss/HyoutaTools#21]
Hello, again. I have problem with rebuild of Music.nub, process freezes after first 8 Mbs of data. Maybe it's related (not sure about though) with previous issues you fixed. Thanks in advance!

**Comment by LabMember12** [comment]
Thanks! Much appreciated.

**Comment by AdmiralCurtiss** [comment]
^ Does this fix your problems?

**Comment by LabMember12** [comment]
Hello, I will try this evening and post about results.
