### ISSUE TITLE
I can`t compile your program!

### ISSUE THREAD

**Issue by hacuraven** [AdmiralCurtiss/HyoutaTools#5]
Hello,
I tried harder , but I can`t compile your program.
I want your Hyoutatools to convert .SE3 to .NUB file in Tales of Vesperia.
PC tells "HyoutaLib.dll and HyoutaLibGUI.dll is not found".
Ionic.Zlib.CF.dll is in Hyoutatools-master folder.

**Comment by AdmiralCurtiss** [comment]
You need to add Ionic.Zlib.CF.dll as a Reference in the 'HyoutaTools' project.

![image](https://user-images.githubusercontent.com/4522237/54721514-844c9380-4b62-11e9-9c00-65c24d0eb163.png)

And then click on 'Browse...' in the window that opens.

As for build order, first build HyoutaPluginBase, then HyoutaTools, then HyoutaToolsCLI. If you also want to run the barebones GUI tools build HyoutaLibGUI and HyoutaToolsGUI.

I should probably clean this up a bit so it's a bit more obvious how to compile this...

**Comment by hacuraven** [comment]
thanks for your advise.
I succeed to make Hyoutatools CLI and GUI.
But CLI is Start-up and end in a moment, and GUI`s run button is no reaction.
Is Argement wrong in GUI?
how to use it?

**Comment by AdmiralCurtiss** [comment]
This is still mainly a command line tool and should be treated as such, even in the barebones GUI mode. Please look up how to use command line tools if you've never used one before.

The sub-tool you want is called `Tales.Vesperia.SE3toNUB`, the arguments it expects are the filename of the input SE3 and the filename of the output NUB. That is, `HyoutaTools Tales.Vesperia.SE3toNUB in.se3 out.nub`

**Comment by hacuraven** [comment]
Sorry,
HyoutaTools CLI answered "Directory 'HyoutaToolsPlugins' not found, not loading any plugins."
"HyoutaToolsPlugin"What is this?

**Comment by AdmiralCurtiss** [comment]
That's fine, you can ignore that, shouldn't affect behavior for what you're trying to do.

(I recently added plugin support to extend the tool functionality with external code.)

**Comment by hacuraven** [comment]
Please help me...
write .bat "HyoutaTools SE3toNUB *.se3 *.nub" 
but,

System.Exception: Loading SE3 failed!
   場所 HyoutaTools.Tales.Vesperia.SE3.SE3..ctor(String filename, Endianness endian, GameTextEncoding encoding) 場所 C:\Users\*\Source\Repos\HyoutaTools\Tales\Vesperia\SE3\SE3.cs:行 12
   場所 HyoutaTools.Tales.Vesperia.SE3.Program.ExtractToNub(List`1 args) 場所 C:\Users\*\Source\Repos\HyoutaTools\Tales\Vesperia\SE3\Program.cs:行 18
   場所 HyoutaTools.LegacyToolWrapper.Execute(List`1 args) 場所 C:\Users\*\Source\Repos\HyoutaTools\Initialization.cs: 行 28
   場所 HyoutaToolsCLI.Program.Main(String[] args) 場所 C:\Users\*\Source\Repos\HyoutaTools\HyoutaToolsCLI\Program.cs: 行 13

HyoutaTools don`t load .SE3 file...

**Comment by AdmiralCurtiss** [comment]
`*.se3` is probably not a valid filename, Windows batch files don't support automatic expansion of wildcards.

You probably want:

`FOR %%G IN (*.se3) DO HyoutaTools SE3toNUB %%G.se3 %%G.nub`

or similar.

**Comment by hacuraven** [comment]
I wrote .bat file...

C:\Users\-\source\repos\HyoutaTools\HyoutaToolsCLI\bin\Release\HyoutaTools.exe　Tales.Vesperia.SE3toNUB 
↓
"Usage SE3toNUB in.se3 out.nub"
↓
C:\Users\-\source\repos\HyoutaTools\HyoutaToolsCLI\bin\Release\HyoutaTools.exe Tales.Vesperia.SE3toNUB C:\Users\-\source\repos\HyoutaTools\HyoutaToolsCLI\bin\Release\test.se3 C:\Users\-\source\repos\HyoutaTools\HyoutaToolsCLI\bin\Release\test.nub
↓
"System.Exception: Loading SE3 failed!"

FOR %%G IN (*.se3) DO HyoutaTools SE3toNUB %%G.se3 %%G.nub
and
FOR %%G IN (*.se3) DO C:\Users\-\source\repos\HyoutaTools\HyoutaToolsCLI\bin\Release\HyoutaTools.exe SE3toNUB C:\Users\-\source\repos\HyoutaTools\HyoutaToolsCLI\bin\Release\%%G.se3 C:\Users\-\source\repos\HyoutaTools\HyoutaToolsCLI\bin\Release\%%G.nub
and
FOR %%G IN (*.se3) DO C:\Users\-\source\repos\HyoutaTools\HyoutaToolsCLI\bin\Release\HyoutaTools.exe SE3toNUB C:\Users\-\source\repos\HyoutaTools\HyoutaToolsCLI\bin\Release\test.se3 C:\Users\-\source\repos\HyoutaTools\HyoutaToolsCLI\bin\Release\test.nub
↓
no reaction...

I don't know what to do...
Sorry, please tell me...

**Comment by AdmiralCurtiss** [comment]
I guess you're trying to use this on the PC Vesperia release? This was written for big endian files and never tested on little endian ones, I just pushed a fix that should hopefully resolve that. Please update and recompile.

**Comment by AdmiralCurtiss** [comment]
I'm gonna close this issue, it's been a good while and I've redone the project files since so you can just open and hit compile (and maybe nuget restore once) and it should work.
